services:
  rails:
    x-cnc:
      type: backend
      migrate: [".", "/root/.profile", "&&", "bundle", "exec", "rails", "db:migrate"]
      system:
        memory: 2G
        cpu: 2
    build:
      context: .
    command: [".", "/root/.profile", "&&", "bundle", "exec", "rails", "server", "-e", "production", "-b", "0.0.0.0"]
  db1:
    x-cnc:
      type: database
      engine: postgres
      version: 13