default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>

development:
  <<: *default
  database: employee_management_development

test:
  <<: *default
  database: employee_management_test

production:
  <<: *default
  database: employee_management_production
  username: employee_management
  password: <%= ENV['EMPLOYEE_MANAGEMENT_DATABASE_PASSWORD'] %>